export const categories = [
  { key: "mensCloth", name: "남성의류" },
  { key: "womansCloth", name: "여성의류" },
  { key: "fashionItems", name: "패션잡화" },
  { key: "shoes", name: "신발" },
  { key: "beauty", name: "화장품/미용" },
  { key: "foods", name: "식품" },
  { key: "babies", name: "출산/육아" },
  { key: "pet", name: "반려동물" },
  { key: "homeAppliances", name: "디지털/가전" },
  { key: "phone_camera", name: "휴대폰/카메라" },
  { key: "PCperipherals", name: "PC 주변기기" },
  { key: "notebook", name: "노트북" },
  { key: "furniture", name: "가구" },
  { key: "interior", name: "조명/인테리어" },
  { key: "homeDeco", name: "패브릭/홈데코" },
  { key: "kitchen", name: "주방용품" },
  { key: "householdGoods", name: "생활용품" },
  { key: "sports", name: "스포츠/레저" },
  { key: "automotiveSupplies", name: "자동차용품" },
  { key: "medical", name: "건강/의료용품" },
  { key: "tools", name: "공구" },
];
